SELECT H.HACKER_ID, H.NAME
FROM HACKERS H JOIN
SUBMISSIONS S ON S.HACKER_ID = H.HACKER_ID JOIN
CHALLENGES C ON C.CHALLENGE_ID = S.CHALLENGE_ID JOIN
DIFFICULTY D ON D.DIFFICULTY_LEVEL = C.DIFFICULTY_LEVEL
WHERE D.DIFFICULTY_LEVEL = C.DIFFICULTY_LEVEL AND S.SCORE = D.SCORE
GROUP BY H.HACKER_ID, H.NAME
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC, H.HACKER_ID;
